<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.ptanhi611</groupId>
    <artifactId>aarithmetic</artifactId>
    <version>1.6</version> 
    <packaging>jar</packaging>   

    <name>Arbitrary Precision Arithmetic</name>
    <description>Sdf project</description>
    <url>https://github.com/ptanhi611/SDF-Arbitary_arthimetic_precision.git</url>

    <developers>
        <developer>
            <id>ptanhi611</id>
            <name>Rishit Mittal</name>
            <email>rishitmittal837@gmail.com</email>
        </developer>
    </developers>

    <build>
        <finalName>aarithmetic</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>21</source>
                    <target>21</target> 
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
